# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lYfprqpJqfkbdoD7fNescO3pZ3zFWRSr
"""

# include the parameters file and emg_samples file over here
from google.colab import files

# This will prompt you to select the 'int_x.txt' file from your computer
uploaded = files.upload()

# maximum and minimum value of the individual emg data in entire file
import re

with open("int_x.txt", "r") as f:
    text = f.read()

numbers = [int(x) for x in re.findall(r"-?\d+", text)]

print("Highest value:", max(numbers))
print("Lowest value:", min(numbers))

# maximum and minimum value of the individual emg data in specified sample
import re
import numpy as np

SAMPLE_INDEX = 14

with open("int_x.txt", "r") as f:
    text = f.read()

numbers = [int(x) for x in re.findall(r"-?\d+", text)]

# Each sample = 1019 time positions × 6 channels
SAMPLE_SIZE = 1019 * 6

start = SAMPLE_INDEX * SAMPLE_SIZE
end = start + SAMPLE_SIZE

sample = numbers[start:end]

if len(sample) != SAMPLE_SIZE:
    raise ValueError("Specified sample does not contain 1019 × 6 values.")

print("Sample:", SAMPLE_INDEX)
print("Highest value:", max(sample))
print("Lowest value:", min(sample))

import re
import ast
import numpy as np
from pathlib import Path

import re
import ast
import numpy as np

# SAMPLE OUTPUT OF THIS BLOCK OF CODE
# First two rows of selected sample:
# [[-52 -25  40   8  19  -5]
#  [-56 -22  32   6  16  -4]]

# ========================================
# SOFTWARE NEURAL NETWORK REFERENCE
# ========================================
# Number of samples : 150
# Selected sample   : 14
# Input shape       : (1019, 6)

# Weight shapes:
# conv1d_8 : (2, 6, 32)  bias: (32,)
# conv1d_9 : (2, 32, 64)  bias: (64,)
# dense_8  : (64, 64)  bias: (64,)
# dense_9  : (64, 6)  bias: (6,)

# Conv1 output
#   Shape       : (1018, 32)
#   First 10    : [-6486   610   625 -3292  1824   365  5418  4415 -2030 -2641]
#   Minimum     : -12674
#   Maximum     : 9348

# ReLU1 output
#   Shape       : (1018, 32)
#   First 10    : [   0  610  625    0 1824  365 5418 4415    0    0]
#   Minimum     : 0
#   Maximum     : 9348

# MaxPool output
#   Shape       : (509, 32)
#   First 10    : [   0 1395  712    0 1824  365 5418 4616    0    0]
#   Minimum     : 0
#   Maximum     : 9348

# Conv2 output
#   Shape       : (508, 64)
#   First 10    : [ 349414  312931  358436  290148  355084  354371 -670406 -624260  418866
#  -175733]
#   Minimum     : -2494441
#   Maximum     : 1892769

# ReLU2 output
#   Shape       : (508, 64)
#   First 10    : [349414 312931 358436 290148 355084 354371      0      0 418866      0]
#   Minimum     : 0
#   Maximum     : 1892769

# Global Average Pool output
#   Shape       : (64,)
#   First 10    : [2.35378026e+05 7.46624016e+04 3.17666858e+05 3.59506614e+04
#  3.96051577e+05 5.27654075e+05 0.00000000e+00 1.85102362e+02
#  2.32878543e+04 2.13197303e+04]
#   Minimum     : 0.0
#   Maximum     : 1172869.037401575

# Dense1 output
#   Shape       : (64,)
#   First 10    : [-4.39536957e+07 -8.52774785e+07  3.29364204e+07  7.25092192e+07
#   5.49777556e+07  3.52027132e+07 -9.15833824e+07  1.15135134e+08
#  -8.86982717e+07  9.54605796e+07]
#   Minimum     : -205540349.06889763
#   Maximum     : 210839570.77952757

# ReLU after Dense1
#   Shape       : (64,)
#   First 10    : [0.00000000e+00 0.00000000e+00 3.29364204e+07 7.25092192e+07
#  5.49777556e+07 3.52027132e+07 0.00000000e+00 1.15135134e+08
#  0.00000000e+00 9.54605796e+07]
#   Minimum     : 0.0
#   Maximum     : 210839570.77952757

# Final logits
#   Shape       : (6,)
#   First 10    : [ 4.40615581e+10  1.32191613e+10  8.71313413e+09 -2.81967190e+10
#  -3.01071306e+10 -2.95761688e+09]
#   Minimum     : -30107130603.200783
#   Maximum     : 44061558055.484245

# Final logits:
# [ 4.40615581e+10  1.32191613e+10  8.71313413e+09 -2.81967190e+10
#  -3.01071306e+10 -2.95761688e+09]

# Softmax probabilities:
# [1. 0. 0. 0. 0. 0.]

# Predicted class: 0

# Full intermediate values saved to:
# intermediate_sample_14.txt

# ============================================================
# SETTINGS
# ============================================================

WEIGHT_FILE = "mp_5_a_pca_ori_model_wt_bias.txt"
SAMPLE_FILE = "int_x.txt"

# Which EMG sample to run.
# There are 150 samples, so valid values are 0 to 149.
SAMPLE_INDEX = 14

# Full intermediate arrays are written to this file.
OUTPUT_FILE = f"intermediate_sample_{SAMPLE_INDEX}.txt"


# ============================================================
# READ EMG SAMPLES
# ============================================================

def load_samples(filename):
    """
    The sample file is formatted approximately as:

    [[[ -49 -6 -2 34 18 2]
      [ -51 -11 2 26 14 1]
      ...
    ]

    Each sample has shape 1019 x 6.
    """

    text = Path(filename).read_text()

    # Extract every integer from the file.
    numbers = [int(x) for x in re.findall(r"-?\d+", text)]

    expected = 150 * 1019 * 6

    if len(numbers) != expected:
        raise ValueError(
            f"Expected {expected} integers in sample file, "
            f"but found {len(numbers)}."
        )

    return np.array(numbers, dtype=np.int64).reshape(150, 1019, 6)


# ============================================================
# READ WEIGHTS AND BIASES
# ============================================================

def load_weights(filename):
    """
    Reads the four layers from the supplied weight text file.

    Expected layers:

        conv1d_8 : (2, 6, 32)
        conv1d_9 : (2, 32, 64)
        dense_8  : (64, 64)
        dense_9  : (64, 6)
    """

    text = Path(filename).read_text()

    layer_names = [
        "conv1d_8",
        "conv1d_9",
        "dense_8",
        "dense_9"
    ]

    result = {}

    for i, name in enumerate(layer_names):

        start = text.index(f"Layer: {name}")

        if i + 1 < len(layer_names):
            end = text.index(f"Layer: {layer_names[i + 1]}")
        else:
            end = len(text)

        section = text[start:end]

        weight_text = section.split(
            "Quantized Weights:", 1
        )[1].split(
            "Quantized Biases:", 1
        )[0].strip()

        bias_text = section.split(
            "Quantized Biases:", 1
        )[1].strip()

        # Remove the dashed separator after the bias.
        bias_text = bias_text.split("-" * 10)[0].strip()

        weights = np.array(
            ast.literal_eval(weight_text),
            dtype=np.int64
        )

        biases = np.array(
            ast.literal_eval(bias_text),
            dtype=np.int64
        )

        result[name] = (weights, biases)

    return result


# ============================================================
# CONVOLUTION
# ============================================================

def conv1d(x, weights, bias):
    """
    Simple valid 1-D convolution/cross-correlation.

    x:
        (time, input_channels)

    weights:
        (kernel_size, input_channels, output_channels)

    output:
        (time-kernel_size+1, output_channels)
    """

    time_length, input_channels = x.shape
    kernel_size, weight_channels, output_channels = weights.shape

    if input_channels != weight_channels:
        raise ValueError("Input channel count does not match weights.")

    output_length = time_length - kernel_size + 1

    output = np.zeros(
        (output_length, output_channels),
        dtype=np.int64
    )

    for t in range(output_length):
      for k in range(kernel_size):
          for c in range(input_channels):
              output[t] += x[t + k, c] * weights[k, c]
      output[t] += bias
    return output

# ============================================================
# PRINT / SAVE INTERMEDIATE VALUES
# ============================================================

def write_array(f, name, array):
    f.write("\n")
    f.write("=" * 70 + "\n")
    f.write(f"{name}\n")
    f.write(f"Shape: {array.shape}\n")
    f.write("=" * 70 + "\n")
    f.write(np.array2string(
        array,
        separator=", ",
        threshold=np.inf,
        max_line_width=200
    ))
    f.write("\n")


def show_summary(name, array):
    flat = array.reshape(-1)

    print(f"\n{name}")
    print(f"  Shape       : {array.shape}")
    print(f"  First 10    : {flat[:10]}")
    print(f"  Minimum     : {flat.min()}")
    print(f"  Maximum     : {flat.max()}")


# ============================================================
# MAIN
# ============================================================

samples = load_samples(SAMPLE_FILE)
weights = load_weights(WEIGHT_FILE)

if not 0 <= SAMPLE_INDEX < len(samples):
    raise ValueError(
        f"SAMPLE_INDEX must be between 0 and {len(samples)-1}"
    )

x = samples[SAMPLE_INDEX]

print("\nFirst two rows of selected sample:")
print(x[:2])

# Get weights and biases.
w1, b1 = weights["conv1d_8"]
w2, b2 = weights["conv1d_9"]
w3, b3 = weights["dense_8"]
w4, b4 = weights["dense_9"]

print("\n========================================")
print("SOFTWARE NEURAL NETWORK REFERENCE")
print("========================================")

print(f"Number of samples : {len(samples)}")
print(f"Selected sample   : {SAMPLE_INDEX}")
print(f"Input shape       : {x.shape}")

print("\nWeight shapes:")
print("conv1d_8 :", w1.shape, " bias:", b1.shape)
print("conv1d_9 :", w2.shape, " bias:", b2.shape)
print("dense_8  :", w3.shape, " bias:", b3.shape)
print("dense_9  :", w4.shape, " bias:", b4.shape)


# ------------------------------------------------------------
# LAYER 1
# ------------------------------------------------------------

conv1 = conv1d(x, w1, b1)
relu1 = np.maximum(conv1, 0)

show_summary("Conv1 output", conv1)
show_summary("ReLU1 output", relu1)


# ------------------------------------------------------------
# MAX POOLING
# ------------------------------------------------------------

# Pool size = 2, stride = 2.
# 1018 becomes 509.

pool1 = relu1.reshape(
    relu1.shape[0] // 2,
    2,
    relu1.shape[1]
).max(axis=1)

show_summary("MaxPool output", pool1)


# ------------------------------------------------------------
# LAYER 2
# ------------------------------------------------------------

conv2 = conv1d(pool1, w2, b2)
relu2 = np.maximum(conv2, 0)

show_summary("Conv2 output", conv2)
show_summary("ReLU2 output", relu2)


# ------------------------------------------------------------
# GLOBAL AVERAGE POOLING
# ------------------------------------------------------------

gap = np.mean(relu2, axis=0)

show_summary("Global Average Pool output", gap)


# ------------------------------------------------------------
# DENSE 1
# ------------------------------------------------------------

dense1 = gap @ w3 + b3
relu3 = np.maximum(dense1, 0)

show_summary("Dense1 output", dense1)
show_summary("ReLU after Dense1", relu3)


# ------------------------------------------------------------
# DENSE 2 / CLASSIFIER
# ------------------------------------------------------------

logits = dense1 @ w4 + b4

# Softmax is only used to get probabilities.
# Prediction itself is simply argmax(logits).
exp_logits = np.exp(logits - np.max(logits))
probabilities = exp_logits / np.sum(exp_logits)

prediction = int(np.argmax(logits))

show_summary("Final logits", logits)

print("\nFinal logits:")
print(logits)

print("\nSoftmax probabilities:")
print(probabilities)

print("\nPredicted class:", prediction)


# ============================================================
# SAVE ALL INTERMEDIATE VALUES
# ============================================================

with open(OUTPUT_FILE, "w") as f:

    f.write("SOFTWARE INTERMEDIATE VALUES\n")
    f.write(f"Sample index: {SAMPLE_INDEX}\n")

    write_array(f, "INPUT", x)

    write_array(f, "CONV1 OUTPUT", conv1)
    write_array(f, "RELU1 OUTPUT", relu1)

    write_array(f, "MAXPOOL OUTPUT", pool1)

    write_array(f, "CONV2 OUTPUT", conv2)
    write_array(f, "RELU2 OUTPUT", relu2)

    write_array(f, "GLOBAL AVERAGE POOL OUTPUT", gap)

    write_array(f, "DENSE1 OUTPUT", dense1)
    write_array(f, "RELU AFTER DENSE1", relu3)

    write_array(f, "FINAL LOGITS", logits)
    write_array(f, "SOFTMAX PROBABILITIES", probabilities)

    f.write("\n")
    f.write("=" * 70 + "\n")
    f.write(f"PREDICTED CLASS: {prediction}\n")
    f.write("=" * 70 + "\n")

print(f"\nFull intermediate values saved to:")
print(OUTPUT_FILE)

import re
import ast
import numpy as np

# I dont fully remember what this block is doing. The hardware had 8-bit quantisation and that was causing issues because baseline model didnt had so. Hence I guess this did the same thing
# as the above block but with 8 bit quantisation applied to each layers ouput


# ============================================================
# SETTINGS
# ============================================================

WEIGHT_FILE = "mp_5_a_pca_ori_model_wt_bias.txt"
SAMPLE_FILE = "int_x.txt"

# Which EMG sample to run.
# There are 150 samples, so valid values are 0 to 149.
SAMPLE_INDEX = 36

# Full intermediate arrays are written to this file.
OUTPUT_FILE = f"intermediate_sample_{SAMPLE_INDEX}.txt"


# ============================================================
# READ EMG SAMPLES
# ============================================================

def load_samples(filename):
    """
    The sample file is formatted approximately as:

    [[[ -49 -6 -2 34 18 2]
      [ -51 -11 2 26 14 1]
      ...
    ]

    Each sample has shape 1019 x 6.
    """

    text = Path(filename).read_text()

    # Extract every integer from the file.
    numbers = [int(x) for x in re.findall(r"-?\d+", text)]

    expected = 150 * 1019 * 6

    if len(numbers) != expected:
        raise ValueError(
            f"Expected {expected} integers in sample file, "
            f"but found {len(numbers)}."
        )

    return np.array(numbers, dtype=np.int64).reshape(150, 1019, 6)


# ============================================================
# READ WEIGHTS AND BIASES
# ============================================================

def load_weights(filename):
    """
    Reads the four layers from the supplied weight text file.

    Expected layers:

        conv1d_8 : (2, 6, 32)
        conv1d_9 : (2, 32, 64)
        dense_8  : (64, 64)
        dense_9  : (64, 6)
    """

    text = Path(filename).read_text()

    layer_names = [
        "conv1d_8",
        "conv1d_9",
        "dense_8",
        "dense_9"
    ]

    result = {}

    for i, name in enumerate(layer_names):

        start = text.index(f"Layer: {name}")

        if i + 1 < len(layer_names):
            end = text.index(f"Layer: {layer_names[i + 1]}")
        else:
            end = len(text)

        section = text[start:end]

        weight_text = section.split(
            "Quantized Weights:", 1
        )[1].split(
            "Quantized Biases:", 1
        )[0].strip()

        bias_text = section.split(
            "Quantized Biases:", 1
        )[1].strip()

        # Remove the dashed separator after the bias.
        bias_text = bias_text.split("-" * 10)[0].strip()

        weights = np.array(
            ast.literal_eval(weight_text),
            dtype=np.int64
        )

        biases = np.array(
            ast.literal_eval(bias_text),
            dtype=np.int64
        )

        result[name] = (weights, biases)

    return result


# ============================================================
# CONVOLUTION
# ============================================================

def conv1d(x, weights, bias):
    """
    Simple valid 1-D convolution/cross-correlation.

    x:
        (time, input_channels)

    weights:
        (kernel_size, input_channels, output_channels)

    output:
        (time-kernel_size+1, output_channels)
    """

    time_length, input_channels = x.shape
    kernel_size, weight_channels, output_channels = weights.shape

    if input_channels != weight_channels:
        raise ValueError("Input channel count does not match weights.")

    output_length = time_length - kernel_size + 1

    output = np.zeros(
        (output_length, output_channels),
        dtype=np.int64
    )

    for t in range(output_length):
      for k in range(kernel_size):
          for c in range(input_channels):
              output[t] += x[t + k, c] * weights[k, c]
      output[t] += bias
    return output

# ============================================================
# PRINT / SAVE INTERMEDIATE VALUES
# ============================================================

def write_array(f, name, array):
    f.write("\n")
    f.write("=" * 70 + "\n")
    f.write(f"{name}\n")
    f.write(f"Shape: {array.shape}\n")
    f.write("=" * 70 + "\n")
    f.write(np.array2string(
        array,
        separator=", ",
        threshold=np.inf,
        max_line_width=200
    ))
    f.write("\n")


def show_summary(name, array):
    flat = array.reshape(-1)

    print(f"\n{name}")
    print(f"  Shape       : {array.shape}")
    print(f"  First 10    : {flat[:10]}")
    print(f"  Minimum     : {flat.min()}")
    print(f"  Maximum     : {flat.max()}")


# ============================================================
# MAIN
# ============================================================

samples = load_samples(SAMPLE_FILE)
weights = load_weights(WEIGHT_FILE)

if not 0 <= SAMPLE_INDEX < len(samples):
    raise ValueError(
        f"SAMPLE_INDEX must be between 0 and {len(samples)-1}"
    )

x = samples[SAMPLE_INDEX]

# ============================================================
# APPLY 8-BIT SIGNED HARDWARE CONSTRAINT
# ============================================================

def to_int8_hardware(x):
    """
    Mimics an 8-bit signed hardware bus.

    Range:
        -128 to +127

    Values outside this range wrap exactly as an 8-bit
    two's-complement hardware signal would.
    """
    return ((x + 128) % 256) - 128


x_raw = samples[SAMPLE_INDEX]

# Raw values from int_x.txt
x = to_int8_hardware(x_raw)

print("\nFirst two rows BEFORE 8-bit conversion:")
print(x_raw[:2])

print("\nFirst two rows AFTER 8-bit signed hardware conversion:")
print(x[:2])

print("\nFirst two rows of selected sample:")
print(x[:2])

# Get weights and biases.
w1, b1 = weights["conv1d_8"]
w2, b2 = weights["conv1d_9"]
w3, b3 = weights["dense_8"]
w4, b4 = weights["dense_9"]

print("\n========================================")
print("SOFTWARE NEURAL NETWORK REFERENCE")
print("========================================")

print(f"Number of samples : {len(samples)}")
print(f"Selected sample   : {SAMPLE_INDEX}")
print(f"Input shape       : {x.shape}")

print("\nWeight shapes:")
print("conv1d_8 :", w1.shape, " bias:", b1.shape)
print("conv1d_9 :", w2.shape, " bias:", b2.shape)
print("dense_8  :", w3.shape, " bias:", b3.shape)
print("dense_9  :", w4.shape, " bias:", b4.shape)


# ------------------------------------------------------------
# LAYER 1
# ------------------------------------------------------------

conv1 = conv1d(x, w1, b1)
relu1 = np.maximum(conv1, 0)

show_summary("Conv1 output", conv1)
show_summary("ReLU1 output", relu1)


# ------------------------------------------------------------
# MAX POOLING
# ------------------------------------------------------------

# Pool size = 2, stride = 2.
# 1018 becomes 509.

pool1 = relu1.reshape(
    relu1.shape[0] // 2,
    2,
    relu1.shape[1]
).max(axis=1)

show_summary("MaxPool output", pool1)


# ------------------------------------------------------------
# LAYER 2
# ------------------------------------------------------------

conv2 = conv1d(pool1, w2, b2)
relu2 = np.maximum(conv2, 0)

show_summary("Conv2 output", conv2)
show_summary("ReLU2 output", relu2)


# ------------------------------------------------------------
# GLOBAL AVERAGE POOLING
# ------------------------------------------------------------

gap = np.mean(relu2, axis=0)

show_summary("Global Average Pool output", gap)


# ------------------------------------------------------------
# DENSE 1
# ------------------------------------------------------------

dense1 = gap @ w3 + b3


show_summary("Dense1 output", dense1)



# ------------------------------------------------------------
# DENSE 2 / CLASSIFIER
# ------------------------------------------------------------

logits = relu @ w4 + b4

# Softmax is only used to get probabilities.
# Prediction itself is simply argmax(logits).
exp_logits = np.exp(logits - np.max(logits))
probabilities = exp_logits / np.sum(exp_logits)

prediction = int(np.argmax(logits))

show_summary("Final logits", logits)

print("\nFinal logits:")
print(logits)

print("\nSoftmax probabilities:")
print(probabilities)

print("\nPredicted class:", prediction)


# ============================================================
# SAVE ALL INTERMEDIATE VALUES
# ============================================================

with open(OUTPUT_FILE, "w") as f:

    f.write("SOFTWARE INTERMEDIATE VALUES\n")
    f.write(f"Sample index: {SAMPLE_INDEX}\n")

    write_array(f, "INPUT", x)

    write_array(f, "CONV1 OUTPUT", conv1)
    write_array(f, "RELU1 OUTPUT", relu1)

    write_array(f, "MAXPOOL OUTPUT", pool1)

    write_array(f, "CONV2 OUTPUT", conv2)
    write_array(f, "RELU2 OUTPUT", relu2)

    write_array(f, "GLOBAL AVERAGE POOL OUTPUT", gap)

    write_array(f, "DENSE1 OUTPUT", dense1)
    write_array(f, "RELU AFTER DENSE1", relu3)

    write_array(f, "FINAL LOGITS", logits)
    write_array(f, "SOFTMAX PROBABILITIES", probabilities)

    f.write("\n")
    f.write("=" * 70 + "\n")
    f.write(f"PREDICTED CLASS: {prediction}\n")
    f.write("=" * 70 + "\n")

print(f"\nFull intermediate values saved to:")
print(OUTPUT_FILE)

#First multiplication and resulting sum of the convolution layer 1
print("Input position 0:", x[0])
print("Input position 1:", x[1])
print("Weights for output channel 0:")
print(w1[:, :, 0])
print("Bias:", b1[0])

terms = []
for k in range(2):
    for c in range(6):
        terms.append(
            (k, c, x[k,c], w1[k,c,0], x[k,c] * w1[k,c,0])
        )

for t in terms:
    print(t)

print("Sum:", sum(t[4] for t in terms) + b1[0])

# ============================================================
# DETAILED CONV2 MULTIPLICATION TRACE
# ============================================================

# Select which Conv2 output to inspect.
# Conv2 output shape = (508, 64)
#
# t = time position
# o = output channel

CONV2_TRACE_T = 0
CONV2_TRACE_CHANNEL = 0

print("\n")
print("=" * 80)
print("DETAILED CONV2 MULTIPLICATION TRACE")
print("=" * 80)

t = CONV2_TRACE_T
o = CONV2_TRACE_CHANNEL

print(f"Conv2 output position : {t}")
print(f"Conv2 output channel  : {o}")

print("\nInput window:")
print(f"pool1[{t}]   = {pool1[t]}")
print(f"pool1[{t+1}] = {pool1[t+1]}")

print("\nWeights for output channel:")
print(f"w2[0, :, {o}] = {w2[0, :, o]}")
print(f"w2[1, :, {o}] = {w2[1, :, o]}")

print(f"\nBias:")
print(f"b2[{o}] = {b2[o]}")

print("\n" + "-" * 80)
print("INDIVIDUAL MULTIPLICATIONS")
print("-" * 80)

total = 0

for k in range(2):
    print(f"\nKernel position k = {k}")

    for c in range(32):
        input_value = pool1[t + k, c]
        weight_value = w2[k, c, o]
        product = input_value * weight_value

        total += product

        print(
            f"  pool1[{t+k},{c}] = {input_value:8d}   "
            f"x   w2[{k},{c},{o}] = {weight_value:8d}"
            f"   ->   {product:12d}"
        )

print("\n" + "-" * 80)
print("ACCUMULATION")
print("-" * 80)

print(f"Sum of 64 products = {total}")
print(f"Bias               = {b2[o]}")
print(f"Conv2 result       = {total} + ({b2[o]})")
print(f"Conv2[{t},{o}]      = {total + b2[o]}")

print("\nPython Conv2 value:")
print(f"conv2[{t},{o}]      = {conv2[t, o]}")

print("\nReLU result:")
print(f"relu2[{t},{o}]      = {relu2[t, o]}")

if total + b2[o] == conv2[t, o]:
    print("\n✓ MANUAL CALCULATION MATCHES CONV2 OUTPUT")
else:
    print("\n✗ MISMATCH")

# ============================================================
# DETAILED CONV2 TRACE - NEXT STRIDE
# ============================================================

CONV2_TRACE_T = 1          # NEXT STRIDE
CONV2_TRACE_CHANNEL = 0    # Output channel to inspect

t = CONV2_TRACE_T
o = CONV2_TRACE_CHANNEL

print("\n")
print("=" * 80)
print("DETAILED CONV2 MULTIPLICATION TRACE")
print("=" * 80)

print(f"Conv2 output position : {t}")
print(f"Conv2 output channel  : {o}")

print("\nInput window:")
print(f"pool1[{t}]   = {pool1[t]}")
print(f"pool1[{t+1}] = {pool1[t+1]}")

print("\nWeights:")
print(f"w2[0, :, {o}] = {w2[0, :, o]}")
print(f"w2[1, :, {o}] = {w2[1, :, o]}")

print("\nBias:")
print(f"b2[{o}] = {b2[o]}")

print("\n" + "-" * 80)
print("INDIVIDUAL MULTIPLICATIONS")
print("-" * 80)

total = 0

for k in range(2):
    print(f"\nKernel position k = {k}")

    for c in range(32):

        input_value = pool1[t + k, c]
        weight_value = w2[k, c, o]
        product = input_value * weight_value

        total += product

        print(
            f"pool1[{t+k},{c}] = {input_value:8d} "
            f"x w2[{k},{c},{o}] = {weight_value:8d} "
            f"-> {product:12d}"
        )

print("\n" + "-" * 80)
print("FINAL ACCUMULATION")
print("-" * 80)

print(f"Sum of 64 products = {total}")
print(f"Bias               = {b2[o]}")
print(f"Conv2 result       = {total} + ({b2[o]})")
print(f"Conv2[{t},{o}]      = {total + b2[o]}")

print("\nPython reference:")
print(f"conv2[{t},{o}]      = {conv2[t, o]}")

print("\nReLU:")
print(f"relu2[{t},{o}]      = {relu2[t, o]}")

if total + b2[o] == conv2[t, o]:
    print("\n✓ MATCH")
else:
    print("\n✗ MISMATCH")

running_sum = 0

for i in range(relu2.shape[0]):
    value = relu2[i, 0]
    running_sum += value
    print(f"Position {i}: value = {value}, running sum = {running_sum}")

print("\nFinal sum =", running_sum)

# ============================================
# Conv2 detailed calculation
# 11th time instant (t = 10)
# Output channel 0
# ============================================

t = 10
          # 11th time instant
oc = 0          # output channel

total = 0

print(f"Conv2[{t}, {oc}] calculation")
print("="*80)

for k in range(2):          # kernel size = 2
    for c in range(32):     # 32 input channels

        x_val = pool1[t + k, c]
        w_val = w2[k, c, oc]
        prod = x_val * w_val

        total += prod

        print(
            f"k={k:1d}, c={c:2d} : "
            f"{x_val:10d} * {w_val:6d} = {prod:12d}"
        )

print("="*80)
print("Bias =", b2[oc])
print("Sum before bias =", total)
print("Final output =", total + b2[oc])
print("Reference from conv2 =", conv2[t, oc])

# ============================================================
# STEP-BY-STEP DENSE1 CALCULATION
# ============================================================

# Dense1:
#   gap      = (64,)
#   w3       = (64, 64)
#   b3       = (64,)
#
# Dense1[j] = sum(gap[i] * w3[i,j]) + b3[j]

print("\n" + "=" * 80)
print("DENSE1 STEP-BY-STEP CALCULATION")
print("=" * 80)

# Choose which Dense1 neuron/output you want to inspect.
# 0 means the first Dense1 output.
OUTPUT_NEURON = 0

print(f"\nCalculating Dense1 output neuron [{OUTPUT_NEURON}]")
print("-" * 80)

running_sum = 0

for i in range(64):

    gap_value = gap[i]
    weight_value = w3[i, OUTPUT_NEURON]

    product = gap_value * weight_value
    running_sum += product

    print(
        f"GAP[{i:2d}] = {gap_value:15.6f}   "
        f"x   W[{i:2d},{OUTPUT_NEURON:2d}] = {weight_value:6d}   "
        f"= {product:18.6f}   "
        f"Running Sum = {running_sum:18.6f}"
    )

print("-" * 80)

print(f"Sum before bias = {running_sum:.6f}")
print(f"Bias[{OUTPUT_NEURON}] = {b3[OUTPUT_NEURON]}")
print(
    f"Dense1[{OUTPUT_NEURON}] = "
    f"{running_sum + b3[OUTPUT_NEURON]:.6f}"
)

print(f"Python Dense1[{OUTPUT_NEURON}] = {dense1[OUTPUT_NEURON]:.6f}")

# Verification
if np.isclose(
    running_sum + b3[OUTPUT_NEURON],
    dense1[OUTPUT_NEURON]
):
    print("\n✓ Calculation matches Dense1 output.")
else:
    print("\n✗ Calculation DOES NOT match Dense1 output.")

# ============================================================
# HARDWARE-ACCURATE 34-BIT SIGNED ADDITION
# ============================================================

def signed_34(value):
    """
    Mimics a signed [33:0] Verilog signal.

    Range:
        -2^33 to 2^33 - 1
    """

    value = int(value)

    # Keep only lower 34 bits
    value = value & ((1 << 34) - 1)

    # Convert to signed two's complement
    if value & (1 << 33):
        value -= (1 << 34)

    return value

# ============================================================
# DENSE 2 - STEP BY STEP CALCULATION
# NO QUANTISATION / NO 34-BIT WRAPPING
# NO ReLU3
# ============================================================

# Dense 2 input = dense1 directly
dense2_input = dense1

# Dense 2 weights and biases
dense2_weights = w4
dense2_bias = b4

print("\n" + "=" * 80)
print("DENSE 2 - STEP BY STEP CALCULATION")
print("NO QUANTISATION / NO 34-BIT WRAPPING")
print("=" * 80)

print("Input shape :", dense2_input.shape)
print("Weight shape:", dense2_weights.shape)
print("Bias shape  :", dense2_bias.shape)


# ============================================================
# DENSE 2 - ADDER TREE
# 64 MULTIPLICATIONS
# ============================================================

dense2_output = np.zeros(6, dtype=np.float64)

for out_neuron in range(6):

    print("\n" + "=" * 80)
    print(f"DENSE2 OUTPUT NEURON {out_neuron}")
    print("=" * 80)

    # --------------------------------------------------------
    # 64 PARALLEL MULTIPLICATIONS
    # --------------------------------------------------------

    products = np.zeros(64, dtype=np.float64)

    for i in range(64):

        products[i] = (
            float(dense2_input[i]) *
            float(dense2_weights[i, out_neuron])
        )

    # --------------------------------------------------------
    # LEVEL 1
    # 64 -> 32
    # --------------------------------------------------------

    q = np.zeros(32, dtype=np.float64)

    for i in range(32):
        q[i] = products[2*i] + products[2*i + 1]

    # --------------------------------------------------------
    # LEVEL 2
    # 32 -> 16
    # --------------------------------------------------------

    w = np.zeros(16, dtype=np.float64)

    for i in range(16):
        w[i] = q[2*i] + q[2*i + 1]

    # --------------------------------------------------------
    # LEVEL 3
    # 16 -> 8
    # --------------------------------------------------------

    e = np.zeros(8, dtype=np.float64)

    for i in range(8):
        e[i] = w[2*i] + w[2*i + 1]

    # --------------------------------------------------------
    # LEVEL 4
    # 8 -> 4
    # --------------------------------------------------------

    r = np.zeros(4, dtype=np.float64)

    for i in range(4):
        r[i] = e[2*i] + e[2*i + 1]

    # --------------------------------------------------------
    # LEVEL 5
    # 4 -> 2
    # --------------------------------------------------------

    t = np.zeros(2, dtype=np.float64)

    for i in range(2):
        t[i] = r[2*i] + r[2*i + 1]

    # --------------------------------------------------------
    # FINAL ADDITION + BIAS
    # --------------------------------------------------------

    bias = float(dense2_bias[out_neuron])

    final_output = t[0] + t[1] + bias

    dense2_output[out_neuron] = final_output

    # ========================================================
    # PRINT RESULTS
    # ========================================================

    print("\n64 MULTIPLICATIONS:")
    for i in range(64):
        print(
            f"Product[{i+1:2d}] = "
            f"{dense2_input[i]} × "
            f"{dense2_weights[i, out_neuron]} "
            f"= {products[i]}"
        )

    print("\n32 ADDITIONS:")
    for i in range(32):
        print(
            f"q[{i}] = Product[{2*i+1}] + "
            f"Product[{2*i+2}] = {q[i]}"
        )

    print("\n16 ADDITIONS:")
    for i in range(16):
        print(
            f"w[{i}] = q[{2*i}] + "
            f"q[{2*i+1}] = {w[i]}"
        )

    print("\n8 ADDITIONS:")
    for i in range(8):
        print(
            f"e[{i}] = w[{2*i}] + "
            f"w[{2*i+1}] = {e[i]}"
        )

    print("\n4 ADDITIONS:")
    for i in range(4):
        print(
            f"r[{i}] = e[{2*i}] + "
            f"e[{2*i+1}] = {r[i]}"
        )

    print("\n2 ADDITIONS:")
    for i in range(2):
        print(
            f"t[{i}] = r[{2*i}] + "
            f"r[{2*i+1}] = {t[i]}"
        )

    print("\nFINAL:")
    print(f"t[0] = {t[0]}")
    print(f"t[1] = {t[1]}")
    print(f"bias  = {bias}")

    print(
        f"Dense2 output[{out_neuron}] = "
        f"{t[0]} + {t[1]} + ({bias})"
    )

    print(
        f"Dense2 output[{out_neuron}] = "
        f"{final_output}"
    )


# ============================================================
# FINAL DENSE2 OUTPUT
# ============================================================

print("\n" + "=" * 80)
print("FINAL DENSE 2 OUTPUTS")
print("=" * 80)

print(dense2_output)


# ============================================================
# DIRECT MATRIX MULTIPLICATION CHECK
# ============================================================

print("\n" + "=" * 80)
print("DIRECT MATRIX MULTIPLICATION CHECK")
print("=" * 80)

dense2_check = (
    dense2_input @ dense2_weights.astype(np.float64)
    + dense2_bias.astype(np.float64)
)

print(dense2_check)